config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'lists#index'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true
  validates :comment, length: { minimum: 6 }

  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: '422'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: '422'
    end
  end

  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a Movie to <%= @list.name %></h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit 'Add bookmark', class: 'btn btn-primary' %>
  <% end %>
  <p><%= link_to 'Back to list', list_path(@list), class: 'btn btn-secondary mt-3' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1562329265-95a6d7a83440?q=80&w=1070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>

<div class="container mt-5">
  <h1 class="mb-4">Movie Lists</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg') %>)">
          <h2 class="card-title">
            <%= link_to list.name, list_path(list), class: "text-decoration-none" %>
          </h2>
      </div>
    <% end %>
  </div>
  <div>
    <p><%= link_to '+ Add a new list', new_list_path, class: 'btn btn-primary mt-3' %></p>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add a List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Add', class: 'btn btn-primary' %>
  <% end %>
  <p><%= link_to 'Back to the movie lists', lists_path, class: 'btn btn-secondary mt-3' %></p>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1562329265-95a6d7a83440?q=80&w=1070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Your personalized list</h1>
  </div>
</div>

<div class="container my-4">
  <h1>The List</h1>
  <div style="border: 1px solid rgba(0,0,0,0.2); border-radius: 10px; padding: 20px; margin-top: 10px;">
    <div class="justify-content-center align-items-center">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path('https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg') %>);
      background-size: cover;
      background-position: center;
      height: 400px;
      ">
        <h2 class="card-title"><%= @list.name %></h2>
      </div>
    </div>
    <p><%= link_to 'Add a movie', new_list_bookmark_path(@list), class: 'btn btn-primary mt-2' %></p>
  </div>

  <div class="container mb-4" style="border: 1px solid rgba(0,0,0,0.2); border-radius: 10px; padding: 20px; margin-top: 10px;">
    <% if @list.bookmarks.any? %>
      <div class="row">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="col-md-4 mb-3">
            <div class="card">
              <%= image_tag bookmark.movie.poster_url, class: "card-img-top", alt: "#{bookmark.movie.title} poster" %>
              <div class="card-body">
                <h2>Bookmark</h2>
                <p class="mb-1"><strong>Movie:</strong> <%= bookmark.movie.title %></p>
                <p><%= bookmark.comment %></p>
                <%= link_to 'Delete bookmark', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Delete this bookmark?' }, class: 'btn btn-danger' %>
              </div>
            </div>
          </div>
        <% end %>
       </div>
    <% else %>
      <p>No Bookmarks yet.</p>
    <% end %>
  </div>
</div>

<div class="text-center mt-4 mb-5">
  <%= link_to 'Back to the movie lists', lists_path, class: 'btn btn-secondary' %>
</div>